/******************************************************************************
 * Copyright AllSeen Alliance. All rights reserved.
 *
 *    Permission to use, copy, modify, and/or distribute this software for any
 *    purpose with or without fee is hereby granted, provided that the above
 *    copyright notice and this permission notice appear in all copies.
 *
 *    THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
 *    WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
 *    MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
 *    ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
 *    WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
 *    ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
 *    OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
 ******************************************************************************/

#ifndef CONTROL_GENERATED_H_
#define CONTROL_GENERATED_H_

#include <alljoyn.h>
#include <alljoyn/controlpanel/Widgets/ActionWidget.h>
#include <alljoyn/controlpanel/Widgets/PropertyWidget.h>
#include <alljoyn/controlpanel/Widgets/ContainerWidget.h>
#include <alljoyn/controlpanel/Widgets/LabelWidget.h>
#include <alljoyn/controlpanel/Widgets/DialogWidget.h>
#include <alljoyn/controlpanel/Common/HttpControl.h>
#include <alljoyn/services_common/ServicesCommon.h>

/**
 * Defines and objectPaths
 */

#define GET_WIDGET_VALUE_CASES \
case EN_SUSIACCESS_CONTROLPANEL_GET_VALUE: \
case EN_SUSIACCESS_BOARDINFOCONTAINER_GET_VALUE: \
case EN_SUSIACCESS_BOARDMANUFACTURERSTRINGPROPERTY_GET_VALUE: \
case EN_SUSIACCESS_BOARDNAMESTRINGPROPERTY_GET_VALUE: \
case EN_SUSIACCESS_VERSIONCONTAINER_GET_VALUE: \
case EN_SUSIACCESS_DRIVERVERSIONPROPERTY_GET_VALUE: \
case EN_SUSIACCESS_LIBRARYVERSIONPROPERTY_GET_VALUE: \
case EN_SUSIACCESS_TEMPERATURECONTAINER_GET_VALUE: \
case EN_SUSIACCESS_TEMPERATUREPROPERTY_GET_VALUE: \
case EN_SUSIACCESS_SUBSCRIPTIONPROPERTY_GET_VALUE: \
case EN_SUSIACCESS_DISPLAYCONTAINER_GET_VALUE: \
case EN_SUSIACCESS_DISPLAYDEVICEPROPERTY_GET_VALUE: \
case EN_SUSIACCESS_BRIGHTNESSPROPERTY_GET_VALUE: \
case EN_SUSIACCESS_BACKLIGHTPROPERTY_GET_VALUE: \
case EN_SUSIACCESS_GPIOCONTAINER_GET_VALUE: \
case EN_SUSIACCESS_GPIOPROPERTY_GET_VALUE: \
case EN_SUSIACCESS_GPIODIRPROPERTY_GET_VALUE: \
case EN_SUSIACCESS_GPIOLEVELPROPERTY_GET_VALUE: \


#define GET_WIDGET_ALL_VALUE_CASES \
case EN_SUSIACCESS_CONTROLPANEL_GET_ALL_VALUES: \
case EN_SUSIACCESS_BOARDINFOCONTAINER_GET_ALL_VALUES: \
case EN_SUSIACCESS_BOARDMANUFACTURERSTRINGPROPERTY_GET_ALL_VALUES: \
case EN_SUSIACCESS_BOARDNAMESTRINGPROPERTY_GET_ALL_VALUES: \
case EN_SUSIACCESS_VERSIONCONTAINER_GET_ALL_VALUES: \
case EN_SUSIACCESS_DRIVERVERSIONPROPERTY_GET_ALL_VALUES: \
case EN_SUSIACCESS_LIBRARYVERSIONPROPERTY_GET_ALL_VALUES: \
case EN_SUSIACCESS_TEMPERATURECONTAINER_GET_ALL_VALUES: \
case EN_SUSIACCESS_TEMPERATUREPROPERTY_GET_ALL_VALUES: \
case EN_SUSIACCESS_SUBSCRIPTIONPROPERTY_GET_ALL_VALUES: \
case EN_SUSIACCESS_DISPLAYCONTAINER_GET_ALL_VALUES: \
case EN_SUSIACCESS_DISPLAYDEVICEPROPERTY_GET_ALL_VALUES: \
case EN_SUSIACCESS_BRIGHTNESSPROPERTY_GET_ALL_VALUES: \
case EN_SUSIACCESS_BACKLIGHTPROPERTY_GET_ALL_VALUES: \
case EN_SUSIACCESS_GPIOCONTAINER_GET_ALL_VALUES: \
case EN_SUSIACCESS_GPIOPROPERTY_GET_ALL_VALUES: \
case EN_SUSIACCESS_GPIODIRPROPERTY_GET_ALL_VALUES: \
case EN_SUSIACCESS_GPIOLEVELPROPERTY_GET_ALL_VALUES: \


#define GET_ROOT_VALUE_CASES \
case SUSIACCESS_ROOT_CONTROLPANEL_CONTROLPANEL_GET_VALUE: \


#define GET_ROOT_ALL_VALUE_CASES \
case SUSIACCESS_ROOT_CONTROLPANEL_CONTROLPANEL_GET_ALL_VALUES: \


#define SET_VALUE_CASES \
case SUSIACCESS_ROOT_CONTROLPANEL_CONTROLPANEL_SET_VALUE: \
case EN_SUSIACCESS_CONTROLPANEL_SET_VALUE: \
case EN_SUSIACCESS_BOARDINFOCONTAINER_SET_VALUE: \
case EN_SUSIACCESS_BOARDMANUFACTURERSTRINGPROPERTY_SET_VALUE: \
case EN_SUSIACCESS_BOARDNAMESTRINGPROPERTY_SET_VALUE: \
case EN_SUSIACCESS_VERSIONCONTAINER_SET_VALUE: \
case EN_SUSIACCESS_DRIVERVERSIONPROPERTY_SET_VALUE: \
case EN_SUSIACCESS_LIBRARYVERSIONPROPERTY_SET_VALUE: \
case EN_SUSIACCESS_TEMPERATURECONTAINER_SET_VALUE: \
case EN_SUSIACCESS_TEMPERATUREPROPERTY_SET_VALUE: \
case EN_SUSIACCESS_SUBSCRIPTIONPROPERTY_SET_VALUE: \
case EN_SUSIACCESS_DISPLAYCONTAINER_SET_VALUE: \
case EN_SUSIACCESS_DISPLAYDEVICEPROPERTY_SET_VALUE: \
case EN_SUSIACCESS_BRIGHTNESSPROPERTY_SET_VALUE: \
case EN_SUSIACCESS_BACKLIGHTPROPERTY_SET_VALUE: \
case EN_SUSIACCESS_GPIOCONTAINER_SET_VALUE: \
case EN_SUSIACCESS_GPIOPROPERTY_SET_VALUE: \
case EN_SUSIACCESS_GPIODIRPROPERTY_SET_VALUE: \
case EN_SUSIACCESS_GPIOLEVELPROPERTY_SET_VALUE: \


#define ACTION_CASES \


#define GET_URL_CASES \


#define AJCPS_CONTROLLEE_GENERATED_OBJECTS \
    {  SUSIAccessControlPanelObjectPath, ControlPanelInterfaces, AJ_OBJ_FLAG_HIDDEN | AJ_OBJ_FLAG_DISABLED | AJ_OBJ_FLAG_ANNOUNCED  }, \
    {  enSUSIAccessControlPanelObjectPath, ContainerInterfaces  }, \
    {  enSUSIAccessBoardInfoContainerObjectPath, ContainerInterfaces  }, \
    {  enSUSIAccessBoardManufacturerStringPropertyObjectPath, PropertyInterfaces  }, \
    {  enSUSIAccessBoardNameStringPropertyObjectPath, PropertyInterfaces  }, \
    {  enSUSIAccessVersionContainerObjectPath, ContainerInterfaces  }, \
    {  enSUSIAccessDriverVersionPropertyObjectPath, PropertyInterfaces  }, \
    {  enSUSIAccessLibraryVersionPropertyObjectPath, PropertyInterfaces  }, \
    {  enSUSIAccessTemperatureContainerObjectPath, ContainerInterfaces  }, \
    {  enSUSIAccessTemperaturePropertyObjectPath, PropertyInterfaces  }, \
    {  enSUSIAccessSubscriptionPropertyObjectPath, PropertyInterfaces  }, \
    {  enSUSIAccessDisplayContainerObjectPath, ContainerInterfaces  }, \
    {  enSUSIAccessDisplayDevicePropertyObjectPath, PropertyInterfaces  }, \
    {  enSUSIAccessBrightnessPropertyObjectPath, PropertyInterfaces  }, \
    {  enSUSIAccessBacklightPropertyObjectPath, PropertyInterfaces  }, \
    {  enSUSIAccessGPIOContainerObjectPath, ContainerInterfaces  }, \
    {  enSUSIAccessGPIOPropertyObjectPath, PropertyInterfaces  }, \
    {  enSUSIAccessGPIODirPropertyObjectPath, PropertyInterfaces  }, \
    {  enSUSIAccessGPIOLevelPropertyObjectPath, PropertyInterfaces  }, \


#define AJCPS_CONTROLLEE_GENERATED_OBJECTS_COUNT               19

#define MAX_NUM_LANGUAGES                                      1

#define SUSIACCESS_MYLANGUAGES_EN 0

#define SUSIACCESS_ROOT_CONTROLPANEL_CONTROLPANEL_GET_VALUE                  AJ_ENCODE_MESSAGE_ID(AJCPS_OBJECT_LIST_INDEX, 0, 0, AJ_PROP_GET)
#define SUSIACCESS_ROOT_CONTROLPANEL_CONTROLPANEL_SET_VALUE                  AJ_ENCODE_MESSAGE_ID(AJCPS_OBJECT_LIST_INDEX, 0, 0, AJ_PROP_SET)
#define SUSIACCESS_ROOT_CONTROLPANEL_CONTROLPANEL_GET_ALL_VALUES             AJ_ENCODE_MESSAGE_ID(AJCPS_OBJECT_LIST_INDEX, 0, 0, AJ_PROP_GET_ALL)
#define SUSIACCESS_ROOT_CONTROLPANEL_CONTROLPANEL_VERSION_PROPERTY           AJ_ENCODE_PROPERTY_ID(AJCPS_OBJECT_LIST_INDEX, 0, 1, 0)

#define EN_SUSIACCESS_CONTROLPANEL_GET_VALUE                  AJ_ENCODE_MESSAGE_ID(AJCPS_OBJECT_LIST_INDEX, 1, 0, AJ_PROP_GET)
#define EN_SUSIACCESS_CONTROLPANEL_SET_VALUE                  AJ_ENCODE_MESSAGE_ID(AJCPS_OBJECT_LIST_INDEX, 1, 0, AJ_PROP_SET)
#define EN_SUSIACCESS_CONTROLPANEL_GET_ALL_VALUES             AJ_ENCODE_MESSAGE_ID(AJCPS_OBJECT_LIST_INDEX, 1, 0, AJ_PROP_GET_ALL)
#define EN_SUSIACCESS_CONTROLPANEL_VERSION_PROPERTY           AJ_ENCODE_PROPERTY_ID(AJCPS_OBJECT_LIST_INDEX, 1, 1, 0)
#define EN_SUSIACCESS_CONTROLPANEL_STATES_PROPERTY            AJ_ENCODE_PROPERTY_ID(AJCPS_OBJECT_LIST_INDEX, 1, 1, 1)
#define EN_SUSIACCESS_CONTROLPANEL_OPTPARAMS_PROPERTY         AJ_ENCODE_PROPERTY_ID(AJCPS_OBJECT_LIST_INDEX, 1, 1, 2)
#define EN_SUSIACCESS_CONTROLPANEL_SIGNAL_PROPERTIES_CHANGED  AJ_ENCODE_MESSAGE_ID(AJCPS_OBJECT_LIST_INDEX, 1, 1, 3)

#define EN_SUSIACCESS_BOARDINFOCONTAINER_GET_VALUE                  AJ_ENCODE_MESSAGE_ID(AJCPS_OBJECT_LIST_INDEX, 2, 0, AJ_PROP_GET)
#define EN_SUSIACCESS_BOARDINFOCONTAINER_SET_VALUE                  AJ_ENCODE_MESSAGE_ID(AJCPS_OBJECT_LIST_INDEX, 2, 0, AJ_PROP_SET)
#define EN_SUSIACCESS_BOARDINFOCONTAINER_GET_ALL_VALUES             AJ_ENCODE_MESSAGE_ID(AJCPS_OBJECT_LIST_INDEX, 2, 0, AJ_PROP_GET_ALL)
#define EN_SUSIACCESS_BOARDINFOCONTAINER_VERSION_PROPERTY           AJ_ENCODE_PROPERTY_ID(AJCPS_OBJECT_LIST_INDEX, 2, 1, 0)
#define EN_SUSIACCESS_BOARDINFOCONTAINER_STATES_PROPERTY            AJ_ENCODE_PROPERTY_ID(AJCPS_OBJECT_LIST_INDEX, 2, 1, 1)
#define EN_SUSIACCESS_BOARDINFOCONTAINER_OPTPARAMS_PROPERTY         AJ_ENCODE_PROPERTY_ID(AJCPS_OBJECT_LIST_INDEX, 2, 1, 2)
#define EN_SUSIACCESS_BOARDINFOCONTAINER_SIGNAL_PROPERTIES_CHANGED  AJ_ENCODE_MESSAGE_ID(AJCPS_OBJECT_LIST_INDEX, 2, 1, 3)

#define EN_SUSIACCESS_BOARDMANUFACTURERSTRINGPROPERTY_GET_VALUE                  AJ_ENCODE_MESSAGE_ID(AJCPS_OBJECT_LIST_INDEX, 3, 0, AJ_PROP_GET)
#define EN_SUSIACCESS_BOARDMANUFACTURERSTRINGPROPERTY_SET_VALUE                  AJ_ENCODE_MESSAGE_ID(AJCPS_OBJECT_LIST_INDEX, 3, 0, AJ_PROP_SET)
#define EN_SUSIACCESS_BOARDMANUFACTURERSTRINGPROPERTY_GET_ALL_VALUES             AJ_ENCODE_MESSAGE_ID(AJCPS_OBJECT_LIST_INDEX, 3, 0, AJ_PROP_GET_ALL)
#define EN_SUSIACCESS_BOARDMANUFACTURERSTRINGPROPERTY_VERSION_PROPERTY           AJ_ENCODE_PROPERTY_ID(AJCPS_OBJECT_LIST_INDEX, 3, 1, 0)
#define EN_SUSIACCESS_BOARDMANUFACTURERSTRINGPROPERTY_STATES_PROPERTY            AJ_ENCODE_PROPERTY_ID(AJCPS_OBJECT_LIST_INDEX, 3, 1, 1)
#define EN_SUSIACCESS_BOARDMANUFACTURERSTRINGPROPERTY_OPTPARAMS_PROPERTY         AJ_ENCODE_PROPERTY_ID(AJCPS_OBJECT_LIST_INDEX, 3, 1, 2)
#define EN_SUSIACCESS_BOARDMANUFACTURERSTRINGPROPERTY_SIGNAL_PROPERTIES_CHANGED  AJ_ENCODE_MESSAGE_ID(AJCPS_OBJECT_LIST_INDEX, 3, 1, 3)
#define EN_SUSIACCESS_BOARDMANUFACTURERSTRINGPROPERTY_VALUE_PROPERTY             AJ_ENCODE_PROPERTY_ID(AJCPS_OBJECT_LIST_INDEX, 3, 1, 4)
#define EN_SUSIACCESS_BOARDMANUFACTURERSTRINGPROPERTY_SIGNAL_VALUE_CHANGED       AJ_ENCODE_MESSAGE_ID(AJCPS_OBJECT_LIST_INDEX, 3, 1, 5)

#define EN_SUSIACCESS_BOARDNAMESTRINGPROPERTY_GET_VALUE                  AJ_ENCODE_MESSAGE_ID(AJCPS_OBJECT_LIST_INDEX, 4, 0, AJ_PROP_GET)
#define EN_SUSIACCESS_BOARDNAMESTRINGPROPERTY_SET_VALUE                  AJ_ENCODE_MESSAGE_ID(AJCPS_OBJECT_LIST_INDEX, 4, 0, AJ_PROP_SET)
#define EN_SUSIACCESS_BOARDNAMESTRINGPROPERTY_GET_ALL_VALUES             AJ_ENCODE_MESSAGE_ID(AJCPS_OBJECT_LIST_INDEX, 4, 0, AJ_PROP_GET_ALL)
#define EN_SUSIACCESS_BOARDNAMESTRINGPROPERTY_VERSION_PROPERTY           AJ_ENCODE_PROPERTY_ID(AJCPS_OBJECT_LIST_INDEX, 4, 1, 0)
#define EN_SUSIACCESS_BOARDNAMESTRINGPROPERTY_STATES_PROPERTY            AJ_ENCODE_PROPERTY_ID(AJCPS_OBJECT_LIST_INDEX, 4, 1, 1)
#define EN_SUSIACCESS_BOARDNAMESTRINGPROPERTY_OPTPARAMS_PROPERTY         AJ_ENCODE_PROPERTY_ID(AJCPS_OBJECT_LIST_INDEX, 4, 1, 2)
#define EN_SUSIACCESS_BOARDNAMESTRINGPROPERTY_SIGNAL_PROPERTIES_CHANGED  AJ_ENCODE_MESSAGE_ID(AJCPS_OBJECT_LIST_INDEX, 4, 1, 3)
#define EN_SUSIACCESS_BOARDNAMESTRINGPROPERTY_VALUE_PROPERTY             AJ_ENCODE_PROPERTY_ID(AJCPS_OBJECT_LIST_INDEX, 4, 1, 4)
#define EN_SUSIACCESS_BOARDNAMESTRINGPROPERTY_SIGNAL_VALUE_CHANGED       AJ_ENCODE_MESSAGE_ID(AJCPS_OBJECT_LIST_INDEX, 4, 1, 5)

#define EN_SUSIACCESS_VERSIONCONTAINER_GET_VALUE                  AJ_ENCODE_MESSAGE_ID(AJCPS_OBJECT_LIST_INDEX, 5, 0, AJ_PROP_GET)
#define EN_SUSIACCESS_VERSIONCONTAINER_SET_VALUE                  AJ_ENCODE_MESSAGE_ID(AJCPS_OBJECT_LIST_INDEX, 5, 0, AJ_PROP_SET)
#define EN_SUSIACCESS_VERSIONCONTAINER_GET_ALL_VALUES             AJ_ENCODE_MESSAGE_ID(AJCPS_OBJECT_LIST_INDEX, 5, 0, AJ_PROP_GET_ALL)
#define EN_SUSIACCESS_VERSIONCONTAINER_VERSION_PROPERTY           AJ_ENCODE_PROPERTY_ID(AJCPS_OBJECT_LIST_INDEX, 5, 1, 0)
#define EN_SUSIACCESS_VERSIONCONTAINER_STATES_PROPERTY            AJ_ENCODE_PROPERTY_ID(AJCPS_OBJECT_LIST_INDEX, 5, 1, 1)
#define EN_SUSIACCESS_VERSIONCONTAINER_OPTPARAMS_PROPERTY         AJ_ENCODE_PROPERTY_ID(AJCPS_OBJECT_LIST_INDEX, 5, 1, 2)
#define EN_SUSIACCESS_VERSIONCONTAINER_SIGNAL_PROPERTIES_CHANGED  AJ_ENCODE_MESSAGE_ID(AJCPS_OBJECT_LIST_INDEX, 5, 1, 3)

#define EN_SUSIACCESS_DRIVERVERSIONPROPERTY_GET_VALUE                  AJ_ENCODE_MESSAGE_ID(AJCPS_OBJECT_LIST_INDEX, 6, 0, AJ_PROP_GET)
#define EN_SUSIACCESS_DRIVERVERSIONPROPERTY_SET_VALUE                  AJ_ENCODE_MESSAGE_ID(AJCPS_OBJECT_LIST_INDEX, 6, 0, AJ_PROP_SET)
#define EN_SUSIACCESS_DRIVERVERSIONPROPERTY_GET_ALL_VALUES             AJ_ENCODE_MESSAGE_ID(AJCPS_OBJECT_LIST_INDEX, 6, 0, AJ_PROP_GET_ALL)
#define EN_SUSIACCESS_DRIVERVERSIONPROPERTY_VERSION_PROPERTY           AJ_ENCODE_PROPERTY_ID(AJCPS_OBJECT_LIST_INDEX, 6, 1, 0)
#define EN_SUSIACCESS_DRIVERVERSIONPROPERTY_STATES_PROPERTY            AJ_ENCODE_PROPERTY_ID(AJCPS_OBJECT_LIST_INDEX, 6, 1, 1)
#define EN_SUSIACCESS_DRIVERVERSIONPROPERTY_OPTPARAMS_PROPERTY         AJ_ENCODE_PROPERTY_ID(AJCPS_OBJECT_LIST_INDEX, 6, 1, 2)
#define EN_SUSIACCESS_DRIVERVERSIONPROPERTY_SIGNAL_PROPERTIES_CHANGED  AJ_ENCODE_MESSAGE_ID(AJCPS_OBJECT_LIST_INDEX, 6, 1, 3)
#define EN_SUSIACCESS_DRIVERVERSIONPROPERTY_VALUE_PROPERTY             AJ_ENCODE_PROPERTY_ID(AJCPS_OBJECT_LIST_INDEX, 6, 1, 4)
#define EN_SUSIACCESS_DRIVERVERSIONPROPERTY_SIGNAL_VALUE_CHANGED       AJ_ENCODE_MESSAGE_ID(AJCPS_OBJECT_LIST_INDEX, 6, 1, 5)

#define EN_SUSIACCESS_LIBRARYVERSIONPROPERTY_GET_VALUE                  AJ_ENCODE_MESSAGE_ID(AJCPS_OBJECT_LIST_INDEX, 7, 0, AJ_PROP_GET)
#define EN_SUSIACCESS_LIBRARYVERSIONPROPERTY_SET_VALUE                  AJ_ENCODE_MESSAGE_ID(AJCPS_OBJECT_LIST_INDEX, 7, 0, AJ_PROP_SET)
#define EN_SUSIACCESS_LIBRARYVERSIONPROPERTY_GET_ALL_VALUES             AJ_ENCODE_MESSAGE_ID(AJCPS_OBJECT_LIST_INDEX, 7, 0, AJ_PROP_GET_ALL)
#define EN_SUSIACCESS_LIBRARYVERSIONPROPERTY_VERSION_PROPERTY           AJ_ENCODE_PROPERTY_ID(AJCPS_OBJECT_LIST_INDEX, 7, 1, 0)
#define EN_SUSIACCESS_LIBRARYVERSIONPROPERTY_STATES_PROPERTY            AJ_ENCODE_PROPERTY_ID(AJCPS_OBJECT_LIST_INDEX, 7, 1, 1)
#define EN_SUSIACCESS_LIBRARYVERSIONPROPERTY_OPTPARAMS_PROPERTY         AJ_ENCODE_PROPERTY_ID(AJCPS_OBJECT_LIST_INDEX, 7, 1, 2)
#define EN_SUSIACCESS_LIBRARYVERSIONPROPERTY_SIGNAL_PROPERTIES_CHANGED  AJ_ENCODE_MESSAGE_ID(AJCPS_OBJECT_LIST_INDEX, 7, 1, 3)
#define EN_SUSIACCESS_LIBRARYVERSIONPROPERTY_VALUE_PROPERTY             AJ_ENCODE_PROPERTY_ID(AJCPS_OBJECT_LIST_INDEX, 7, 1, 4)
#define EN_SUSIACCESS_LIBRARYVERSIONPROPERTY_SIGNAL_VALUE_CHANGED       AJ_ENCODE_MESSAGE_ID(AJCPS_OBJECT_LIST_INDEX, 7, 1, 5)

#define EN_SUSIACCESS_TEMPERATURECONTAINER_GET_VALUE                  AJ_ENCODE_MESSAGE_ID(AJCPS_OBJECT_LIST_INDEX, 8, 0, AJ_PROP_GET)
#define EN_SUSIACCESS_TEMPERATURECONTAINER_SET_VALUE                  AJ_ENCODE_MESSAGE_ID(AJCPS_OBJECT_LIST_INDEX, 8, 0, AJ_PROP_SET)
#define EN_SUSIACCESS_TEMPERATURECONTAINER_GET_ALL_VALUES             AJ_ENCODE_MESSAGE_ID(AJCPS_OBJECT_LIST_INDEX, 8, 0, AJ_PROP_GET_ALL)
#define EN_SUSIACCESS_TEMPERATURECONTAINER_VERSION_PROPERTY           AJ_ENCODE_PROPERTY_ID(AJCPS_OBJECT_LIST_INDEX, 8, 1, 0)
#define EN_SUSIACCESS_TEMPERATURECONTAINER_STATES_PROPERTY            AJ_ENCODE_PROPERTY_ID(AJCPS_OBJECT_LIST_INDEX, 8, 1, 1)
#define EN_SUSIACCESS_TEMPERATURECONTAINER_OPTPARAMS_PROPERTY         AJ_ENCODE_PROPERTY_ID(AJCPS_OBJECT_LIST_INDEX, 8, 1, 2)
#define EN_SUSIACCESS_TEMPERATURECONTAINER_SIGNAL_PROPERTIES_CHANGED  AJ_ENCODE_MESSAGE_ID(AJCPS_OBJECT_LIST_INDEX, 8, 1, 3)

#define EN_SUSIACCESS_TEMPERATUREPROPERTY_GET_VALUE                  AJ_ENCODE_MESSAGE_ID(AJCPS_OBJECT_LIST_INDEX, 9, 0, AJ_PROP_GET)
#define EN_SUSIACCESS_TEMPERATUREPROPERTY_SET_VALUE                  AJ_ENCODE_MESSAGE_ID(AJCPS_OBJECT_LIST_INDEX, 9, 0, AJ_PROP_SET)
#define EN_SUSIACCESS_TEMPERATUREPROPERTY_GET_ALL_VALUES             AJ_ENCODE_MESSAGE_ID(AJCPS_OBJECT_LIST_INDEX, 9, 0, AJ_PROP_GET_ALL)
#define EN_SUSIACCESS_TEMPERATUREPROPERTY_VERSION_PROPERTY           AJ_ENCODE_PROPERTY_ID(AJCPS_OBJECT_LIST_INDEX, 9, 1, 0)
#define EN_SUSIACCESS_TEMPERATUREPROPERTY_STATES_PROPERTY            AJ_ENCODE_PROPERTY_ID(AJCPS_OBJECT_LIST_INDEX, 9, 1, 1)
#define EN_SUSIACCESS_TEMPERATUREPROPERTY_OPTPARAMS_PROPERTY         AJ_ENCODE_PROPERTY_ID(AJCPS_OBJECT_LIST_INDEX, 9, 1, 2)
#define EN_SUSIACCESS_TEMPERATUREPROPERTY_SIGNAL_PROPERTIES_CHANGED  AJ_ENCODE_MESSAGE_ID(AJCPS_OBJECT_LIST_INDEX, 9, 1, 3)
#define EN_SUSIACCESS_TEMPERATUREPROPERTY_VALUE_PROPERTY             AJ_ENCODE_PROPERTY_ID(AJCPS_OBJECT_LIST_INDEX, 9, 1, 4)
#define EN_SUSIACCESS_TEMPERATUREPROPERTY_SIGNAL_VALUE_CHANGED       AJ_ENCODE_MESSAGE_ID(AJCPS_OBJECT_LIST_INDEX, 9, 1, 5)

#define EN_SUSIACCESS_SUBSCRIPTIONPROPERTY_GET_VALUE                  AJ_ENCODE_MESSAGE_ID(AJCPS_OBJECT_LIST_INDEX, 10, 0, AJ_PROP_GET)
#define EN_SUSIACCESS_SUBSCRIPTIONPROPERTY_SET_VALUE                  AJ_ENCODE_MESSAGE_ID(AJCPS_OBJECT_LIST_INDEX, 10, 0, AJ_PROP_SET)
#define EN_SUSIACCESS_SUBSCRIPTIONPROPERTY_GET_ALL_VALUES             AJ_ENCODE_MESSAGE_ID(AJCPS_OBJECT_LIST_INDEX, 10, 0, AJ_PROP_GET_ALL)
#define EN_SUSIACCESS_SUBSCRIPTIONPROPERTY_VERSION_PROPERTY           AJ_ENCODE_PROPERTY_ID(AJCPS_OBJECT_LIST_INDEX, 10, 1, 0)
#define EN_SUSIACCESS_SUBSCRIPTIONPROPERTY_STATES_PROPERTY            AJ_ENCODE_PROPERTY_ID(AJCPS_OBJECT_LIST_INDEX, 10, 1, 1)
#define EN_SUSIACCESS_SUBSCRIPTIONPROPERTY_OPTPARAMS_PROPERTY         AJ_ENCODE_PROPERTY_ID(AJCPS_OBJECT_LIST_INDEX, 10, 1, 2)
#define EN_SUSIACCESS_SUBSCRIPTIONPROPERTY_SIGNAL_PROPERTIES_CHANGED  AJ_ENCODE_MESSAGE_ID(AJCPS_OBJECT_LIST_INDEX, 10, 1, 3)
#define EN_SUSIACCESS_SUBSCRIPTIONPROPERTY_VALUE_PROPERTY             AJ_ENCODE_PROPERTY_ID(AJCPS_OBJECT_LIST_INDEX, 10, 1, 4)
#define EN_SUSIACCESS_SUBSCRIPTIONPROPERTY_SIGNAL_VALUE_CHANGED       AJ_ENCODE_MESSAGE_ID(AJCPS_OBJECT_LIST_INDEX, 10, 1, 5)

#define EN_SUSIACCESS_DISPLAYCONTAINER_GET_VALUE                  AJ_ENCODE_MESSAGE_ID(AJCPS_OBJECT_LIST_INDEX, 11, 0, AJ_PROP_GET)
#define EN_SUSIACCESS_DISPLAYCONTAINER_SET_VALUE                  AJ_ENCODE_MESSAGE_ID(AJCPS_OBJECT_LIST_INDEX, 11, 0, AJ_PROP_SET)
#define EN_SUSIACCESS_DISPLAYCONTAINER_GET_ALL_VALUES             AJ_ENCODE_MESSAGE_ID(AJCPS_OBJECT_LIST_INDEX, 11, 0, AJ_PROP_GET_ALL)
#define EN_SUSIACCESS_DISPLAYCONTAINER_VERSION_PROPERTY           AJ_ENCODE_PROPERTY_ID(AJCPS_OBJECT_LIST_INDEX, 11, 1, 0)
#define EN_SUSIACCESS_DISPLAYCONTAINER_STATES_PROPERTY            AJ_ENCODE_PROPERTY_ID(AJCPS_OBJECT_LIST_INDEX, 11, 1, 1)
#define EN_SUSIACCESS_DISPLAYCONTAINER_OPTPARAMS_PROPERTY         AJ_ENCODE_PROPERTY_ID(AJCPS_OBJECT_LIST_INDEX, 11, 1, 2)
#define EN_SUSIACCESS_DISPLAYCONTAINER_SIGNAL_PROPERTIES_CHANGED  AJ_ENCODE_MESSAGE_ID(AJCPS_OBJECT_LIST_INDEX, 11, 1, 3)

#define EN_SUSIACCESS_DISPLAYDEVICEPROPERTY_GET_VALUE                  AJ_ENCODE_MESSAGE_ID(AJCPS_OBJECT_LIST_INDEX, 12, 0, AJ_PROP_GET)
#define EN_SUSIACCESS_DISPLAYDEVICEPROPERTY_SET_VALUE                  AJ_ENCODE_MESSAGE_ID(AJCPS_OBJECT_LIST_INDEX, 12, 0, AJ_PROP_SET)
#define EN_SUSIACCESS_DISPLAYDEVICEPROPERTY_GET_ALL_VALUES             AJ_ENCODE_MESSAGE_ID(AJCPS_OBJECT_LIST_INDEX, 12, 0, AJ_PROP_GET_ALL)
#define EN_SUSIACCESS_DISPLAYDEVICEPROPERTY_VERSION_PROPERTY           AJ_ENCODE_PROPERTY_ID(AJCPS_OBJECT_LIST_INDEX, 12, 1, 0)
#define EN_SUSIACCESS_DISPLAYDEVICEPROPERTY_STATES_PROPERTY            AJ_ENCODE_PROPERTY_ID(AJCPS_OBJECT_LIST_INDEX, 12, 1, 1)
#define EN_SUSIACCESS_DISPLAYDEVICEPROPERTY_OPTPARAMS_PROPERTY         AJ_ENCODE_PROPERTY_ID(AJCPS_OBJECT_LIST_INDEX, 12, 1, 2)
#define EN_SUSIACCESS_DISPLAYDEVICEPROPERTY_SIGNAL_PROPERTIES_CHANGED  AJ_ENCODE_MESSAGE_ID(AJCPS_OBJECT_LIST_INDEX, 12, 1, 3)
#define EN_SUSIACCESS_DISPLAYDEVICEPROPERTY_VALUE_PROPERTY             AJ_ENCODE_PROPERTY_ID(AJCPS_OBJECT_LIST_INDEX, 12, 1, 4)
#define EN_SUSIACCESS_DISPLAYDEVICEPROPERTY_SIGNAL_VALUE_CHANGED       AJ_ENCODE_MESSAGE_ID(AJCPS_OBJECT_LIST_INDEX, 12, 1, 5)

#define EN_SUSIACCESS_BRIGHTNESSPROPERTY_GET_VALUE                  AJ_ENCODE_MESSAGE_ID(AJCPS_OBJECT_LIST_INDEX, 13, 0, AJ_PROP_GET)
#define EN_SUSIACCESS_BRIGHTNESSPROPERTY_SET_VALUE                  AJ_ENCODE_MESSAGE_ID(AJCPS_OBJECT_LIST_INDEX, 13, 0, AJ_PROP_SET)
#define EN_SUSIACCESS_BRIGHTNESSPROPERTY_GET_ALL_VALUES             AJ_ENCODE_MESSAGE_ID(AJCPS_OBJECT_LIST_INDEX, 13, 0, AJ_PROP_GET_ALL)
#define EN_SUSIACCESS_BRIGHTNESSPROPERTY_VERSION_PROPERTY           AJ_ENCODE_PROPERTY_ID(AJCPS_OBJECT_LIST_INDEX, 13, 1, 0)
#define EN_SUSIACCESS_BRIGHTNESSPROPERTY_STATES_PROPERTY            AJ_ENCODE_PROPERTY_ID(AJCPS_OBJECT_LIST_INDEX, 13, 1, 1)
#define EN_SUSIACCESS_BRIGHTNESSPROPERTY_OPTPARAMS_PROPERTY         AJ_ENCODE_PROPERTY_ID(AJCPS_OBJECT_LIST_INDEX, 13, 1, 2)
#define EN_SUSIACCESS_BRIGHTNESSPROPERTY_SIGNAL_PROPERTIES_CHANGED  AJ_ENCODE_MESSAGE_ID(AJCPS_OBJECT_LIST_INDEX, 13, 1, 3)
#define EN_SUSIACCESS_BRIGHTNESSPROPERTY_VALUE_PROPERTY             AJ_ENCODE_PROPERTY_ID(AJCPS_OBJECT_LIST_INDEX, 13, 1, 4)
#define EN_SUSIACCESS_BRIGHTNESSPROPERTY_SIGNAL_VALUE_CHANGED       AJ_ENCODE_MESSAGE_ID(AJCPS_OBJECT_LIST_INDEX, 13, 1, 5)

#define EN_SUSIACCESS_BACKLIGHTPROPERTY_GET_VALUE                  AJ_ENCODE_MESSAGE_ID(AJCPS_OBJECT_LIST_INDEX, 14, 0, AJ_PROP_GET)
#define EN_SUSIACCESS_BACKLIGHTPROPERTY_SET_VALUE                  AJ_ENCODE_MESSAGE_ID(AJCPS_OBJECT_LIST_INDEX, 14, 0, AJ_PROP_SET)
#define EN_SUSIACCESS_BACKLIGHTPROPERTY_GET_ALL_VALUES             AJ_ENCODE_MESSAGE_ID(AJCPS_OBJECT_LIST_INDEX, 14, 0, AJ_PROP_GET_ALL)
#define EN_SUSIACCESS_BACKLIGHTPROPERTY_VERSION_PROPERTY           AJ_ENCODE_PROPERTY_ID(AJCPS_OBJECT_LIST_INDEX, 14, 1, 0)
#define EN_SUSIACCESS_BACKLIGHTPROPERTY_STATES_PROPERTY            AJ_ENCODE_PROPERTY_ID(AJCPS_OBJECT_LIST_INDEX, 14, 1, 1)
#define EN_SUSIACCESS_BACKLIGHTPROPERTY_OPTPARAMS_PROPERTY         AJ_ENCODE_PROPERTY_ID(AJCPS_OBJECT_LIST_INDEX, 14, 1, 2)
#define EN_SUSIACCESS_BACKLIGHTPROPERTY_SIGNAL_PROPERTIES_CHANGED  AJ_ENCODE_MESSAGE_ID(AJCPS_OBJECT_LIST_INDEX, 14, 1, 3)
#define EN_SUSIACCESS_BACKLIGHTPROPERTY_VALUE_PROPERTY             AJ_ENCODE_PROPERTY_ID(AJCPS_OBJECT_LIST_INDEX, 14, 1, 4)
#define EN_SUSIACCESS_BACKLIGHTPROPERTY_SIGNAL_VALUE_CHANGED       AJ_ENCODE_MESSAGE_ID(AJCPS_OBJECT_LIST_INDEX, 14, 1, 5)

#define EN_SUSIACCESS_GPIOCONTAINER_GET_VALUE                  AJ_ENCODE_MESSAGE_ID(AJCPS_OBJECT_LIST_INDEX, 15, 0, AJ_PROP_GET)
#define EN_SUSIACCESS_GPIOCONTAINER_SET_VALUE                  AJ_ENCODE_MESSAGE_ID(AJCPS_OBJECT_LIST_INDEX, 15, 0, AJ_PROP_SET)
#define EN_SUSIACCESS_GPIOCONTAINER_GET_ALL_VALUES             AJ_ENCODE_MESSAGE_ID(AJCPS_OBJECT_LIST_INDEX, 15, 0, AJ_PROP_GET_ALL)
#define EN_SUSIACCESS_GPIOCONTAINER_VERSION_PROPERTY           AJ_ENCODE_PROPERTY_ID(AJCPS_OBJECT_LIST_INDEX, 15, 1, 0)
#define EN_SUSIACCESS_GPIOCONTAINER_STATES_PROPERTY            AJ_ENCODE_PROPERTY_ID(AJCPS_OBJECT_LIST_INDEX, 15, 1, 1)
#define EN_SUSIACCESS_GPIOCONTAINER_OPTPARAMS_PROPERTY         AJ_ENCODE_PROPERTY_ID(AJCPS_OBJECT_LIST_INDEX, 15, 1, 2)
#define EN_SUSIACCESS_GPIOCONTAINER_SIGNAL_PROPERTIES_CHANGED  AJ_ENCODE_MESSAGE_ID(AJCPS_OBJECT_LIST_INDEX, 15, 1, 3)

#define EN_SUSIACCESS_GPIOPROPERTY_GET_VALUE                  AJ_ENCODE_MESSAGE_ID(AJCPS_OBJECT_LIST_INDEX, 16, 0, AJ_PROP_GET)
#define EN_SUSIACCESS_GPIOPROPERTY_SET_VALUE                  AJ_ENCODE_MESSAGE_ID(AJCPS_OBJECT_LIST_INDEX, 16, 0, AJ_PROP_SET)
#define EN_SUSIACCESS_GPIOPROPERTY_GET_ALL_VALUES             AJ_ENCODE_MESSAGE_ID(AJCPS_OBJECT_LIST_INDEX, 16, 0, AJ_PROP_GET_ALL)
#define EN_SUSIACCESS_GPIOPROPERTY_VERSION_PROPERTY           AJ_ENCODE_PROPERTY_ID(AJCPS_OBJECT_LIST_INDEX, 16, 1, 0)
#define EN_SUSIACCESS_GPIOPROPERTY_STATES_PROPERTY            AJ_ENCODE_PROPERTY_ID(AJCPS_OBJECT_LIST_INDEX, 16, 1, 1)
#define EN_SUSIACCESS_GPIOPROPERTY_OPTPARAMS_PROPERTY         AJ_ENCODE_PROPERTY_ID(AJCPS_OBJECT_LIST_INDEX, 16, 1, 2)
#define EN_SUSIACCESS_GPIOPROPERTY_SIGNAL_PROPERTIES_CHANGED  AJ_ENCODE_MESSAGE_ID(AJCPS_OBJECT_LIST_INDEX, 16, 1, 3)
#define EN_SUSIACCESS_GPIOPROPERTY_VALUE_PROPERTY             AJ_ENCODE_PROPERTY_ID(AJCPS_OBJECT_LIST_INDEX, 16, 1, 4)
#define EN_SUSIACCESS_GPIOPROPERTY_SIGNAL_VALUE_CHANGED       AJ_ENCODE_MESSAGE_ID(AJCPS_OBJECT_LIST_INDEX, 16, 1, 5)

#define EN_SUSIACCESS_GPIODIRPROPERTY_GET_VALUE                  AJ_ENCODE_MESSAGE_ID(AJCPS_OBJECT_LIST_INDEX, 17, 0, AJ_PROP_GET)
#define EN_SUSIACCESS_GPIODIRPROPERTY_SET_VALUE                  AJ_ENCODE_MESSAGE_ID(AJCPS_OBJECT_LIST_INDEX, 17, 0, AJ_PROP_SET)
#define EN_SUSIACCESS_GPIODIRPROPERTY_GET_ALL_VALUES             AJ_ENCODE_MESSAGE_ID(AJCPS_OBJECT_LIST_INDEX, 17, 0, AJ_PROP_GET_ALL)
#define EN_SUSIACCESS_GPIODIRPROPERTY_VERSION_PROPERTY           AJ_ENCODE_PROPERTY_ID(AJCPS_OBJECT_LIST_INDEX, 17, 1, 0)
#define EN_SUSIACCESS_GPIODIRPROPERTY_STATES_PROPERTY            AJ_ENCODE_PROPERTY_ID(AJCPS_OBJECT_LIST_INDEX, 17, 1, 1)
#define EN_SUSIACCESS_GPIODIRPROPERTY_OPTPARAMS_PROPERTY         AJ_ENCODE_PROPERTY_ID(AJCPS_OBJECT_LIST_INDEX, 17, 1, 2)
#define EN_SUSIACCESS_GPIODIRPROPERTY_SIGNAL_PROPERTIES_CHANGED  AJ_ENCODE_MESSAGE_ID(AJCPS_OBJECT_LIST_INDEX, 17, 1, 3)
#define EN_SUSIACCESS_GPIODIRPROPERTY_VALUE_PROPERTY             AJ_ENCODE_PROPERTY_ID(AJCPS_OBJECT_LIST_INDEX, 17, 1, 4)
#define EN_SUSIACCESS_GPIODIRPROPERTY_SIGNAL_VALUE_CHANGED       AJ_ENCODE_MESSAGE_ID(AJCPS_OBJECT_LIST_INDEX, 17, 1, 5)

#define EN_SUSIACCESS_GPIOLEVELPROPERTY_GET_VALUE                  AJ_ENCODE_MESSAGE_ID(AJCPS_OBJECT_LIST_INDEX, 18, 0, AJ_PROP_GET)
#define EN_SUSIACCESS_GPIOLEVELPROPERTY_SET_VALUE                  AJ_ENCODE_MESSAGE_ID(AJCPS_OBJECT_LIST_INDEX, 18, 0, AJ_PROP_SET)
#define EN_SUSIACCESS_GPIOLEVELPROPERTY_GET_ALL_VALUES             AJ_ENCODE_MESSAGE_ID(AJCPS_OBJECT_LIST_INDEX, 18, 0, AJ_PROP_GET_ALL)
#define EN_SUSIACCESS_GPIOLEVELPROPERTY_VERSION_PROPERTY           AJ_ENCODE_PROPERTY_ID(AJCPS_OBJECT_LIST_INDEX, 18, 1, 0)
#define EN_SUSIACCESS_GPIOLEVELPROPERTY_STATES_PROPERTY            AJ_ENCODE_PROPERTY_ID(AJCPS_OBJECT_LIST_INDEX, 18, 1, 1)
#define EN_SUSIACCESS_GPIOLEVELPROPERTY_OPTPARAMS_PROPERTY         AJ_ENCODE_PROPERTY_ID(AJCPS_OBJECT_LIST_INDEX, 18, 1, 2)
#define EN_SUSIACCESS_GPIOLEVELPROPERTY_SIGNAL_PROPERTIES_CHANGED  AJ_ENCODE_MESSAGE_ID(AJCPS_OBJECT_LIST_INDEX, 18, 1, 3)
#define EN_SUSIACCESS_GPIOLEVELPROPERTY_VALUE_PROPERTY             AJ_ENCODE_PROPERTY_ID(AJCPS_OBJECT_LIST_INDEX, 18, 1, 4)
#define EN_SUSIACCESS_GPIOLEVELPROPERTY_SIGNAL_VALUE_CHANGED       AJ_ENCODE_MESSAGE_ID(AJCPS_OBJECT_LIST_INDEX, 18, 1, 5)



extern const char SUSIAccessControlPanelObjectPath[];
extern const char enSUSIAccessControlPanelObjectPath[];
extern const char enSUSIAccessBoardInfoContainerObjectPath[];
extern const char enSUSIAccessBoardManufacturerStringPropertyObjectPath[];
extern const char enSUSIAccessBoardNameStringPropertyObjectPath[];
extern const char enSUSIAccessVersionContainerObjectPath[];
extern const char enSUSIAccessDriverVersionPropertyObjectPath[];
extern const char enSUSIAccessLibraryVersionPropertyObjectPath[];
extern const char enSUSIAccessTemperatureContainerObjectPath[];
extern const char enSUSIAccessTemperaturePropertyObjectPath[];
extern const char enSUSIAccessSubscriptionPropertyObjectPath[];
extern const char enSUSIAccessDisplayContainerObjectPath[];
extern const char enSUSIAccessDisplayDevicePropertyObjectPath[];
extern const char enSUSIAccessBrightnessPropertyObjectPath[];
extern const char enSUSIAccessBacklightPropertyObjectPath[];
extern const char enSUSIAccessGPIOContainerObjectPath[];
extern const char enSUSIAccessGPIOPropertyObjectPath[];
extern const char enSUSIAccessGPIODirPropertyObjectPath[];
extern const char enSUSIAccessGPIOLevelPropertyObjectPath[];


extern ContainerWidget SUSIAccessControlPanel;
extern ContainerWidget SUSIAccessBoardInfoContainer;
extern PropertyWidget SUSIAccessBoardManufacturerStringProperty;
extern PropertyWidget SUSIAccessBoardNameStringProperty;
extern ContainerWidget SUSIAccessVersionContainer;
extern PropertyWidget SUSIAccessDriverVersionProperty;
extern PropertyWidget SUSIAccessLibraryVersionProperty;
extern ContainerWidget SUSIAccessTemperatureContainer;
extern PropertyWidget SUSIAccessTemperatureProperty;
extern PropertyWidget SUSIAccessSubscriptionProperty;
extern ContainerWidget SUSIAccessDisplayContainer;
extern PropertyWidget SUSIAccessDisplayDeviceProperty;
extern PropertyWidget SUSIAccessBrightnessProperty;
extern PropertyWidget SUSIAccessBacklightProperty;
extern ContainerWidget SUSIAccessGPIOContainer;
extern PropertyWidget SUSIAccessGPIOProperty;
extern PropertyWidget SUSIAccessGPIODirProperty;
extern PropertyWidget SUSIAccessGPIOLevelProperty;


typedef struct {
    const char* sender;
    uint16_t numSignals;
    int32_t signals[MAX_NUM_LANGUAGES];
} SetValueContext;

typedef struct {
    uint8_t signalType;
    int32_t signalId;
} Signal;

typedef struct {
    uint16_t numSignals;
    Signal signals[MAX_NUM_LANGUAGES * 2];
} ExecuteActionContext;
/**
 *
 * @return
 */
void WidgetsInit();

/**
 * Set Value of a property.
 * @param replyMsg - reply message
 * @param propId - id of property being changed
 * @param context - setvaluecontext. can be used to send signals
 * @return status
 */
AJ_Status SetValueProperty(AJ_Message* replyMsg, uint32_t propId, void* context);

/**
 * Execute Action
 * @param msg - the msg for the response
 * @param msgId - the Action being executed
 * @param context - ExecuteActionContext used to send signals as a result of action
 * @return status
 */
AJ_Status ExecuteAction(AJ_Message* msg, uint32_t msgId, ExecuteActionContext* context);


/* Defines and functions for Tester App */
typedef struct {
    uint32_t msgId;
    uint16_t numParams;
    uint16_t param[3];
} CPSTest;

#define NUMBER_OF_TESTS //NUM_TESTS_GO_HERE

#define ALL_REPLY_CASES                //ALL_REPLIES_GO_HERE

void TestsInit(CPSTest* testsToRun);

void* IdentifyMsgOrPropId(uint32_t identifier, uint16_t* widgetType, uint16_t* propType, uint16_t* language);
void* IdentifyMsgOrPropIdForSignal(uint32_t identifier, uint8_t* isProperty);
uint8_t IdentifyRootMsgOrPropId(uint32_t identifier);
AJSVC_ServiceStatus GeneratedMessageProcessor(AJ_BusAttachment* bus, AJ_Message* msg, AJ_Status* msgStatus);

#endif /* CONTROL_GENERATED_H_ */
